stages:
  data_ingestion:
    cmd: python src/datas/data_ingestion.py
    params:
    - data_ingestion.test_size
    deps:
    - src/datas/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/datas/data_preprocessing.py
    deps:
    - data/raw
    - src/datas/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/datas/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - metrics.json
    outs:
    - reports/metrics.json